### ISSUE TITLE
git clone requires username/password

### ISSUE THREAD

**Issue by whitis** [sergev/yaesutool#1]
git clone requires username/password for yeasutool but not baoclone.
This is unacceptable since it is being used in a script to install a variety of ham radio software.

First problem is that you gave an https URL in README.md but even after changing it to a http URL, the problem persists, so it would appear that you have the repository configured to require login even if you aren't making changes.

**Comment by sergev** [comment]
Does this problem still persist?

**Comment by watsoncj** [comment]
This can be closed.

Verified on fresh Ubuntu20 that no GitHub credentials are required.

```
root@ubuntu20:/tmp# git clone https://github.com/sergev/yaesutool.git
Cloning into 'yaesutool'...
remote: Enumerating objects: 134, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 134 (delta 0), reused 1 (delta 0), pack-reused 127
Receiving objects: 100% (134/134), 72.32 KiB | 892.00 KiB/s, done.
Resolving deltas: 100% (77/77), done.
```

**Comment by sergev** [comment]
Thank you for confirming. Closed.
