### ISSUE TITLE
Compile issues on Fedora 37

### ISSUE THREAD

**Issue by wedgef5** [sergev/yaesutool#3]
There are issues with the way the following global variables are declared and defined in the application: serial_verbose, radio_port and radio_progress. I had to make adjustments in util.h, radio.h, main.c, and radio.c  to have the application compile and link without errors.

**Comment by sergev** [comment]
Thank you for bug report. Can you please try this version: https://github.com/sergev/yaesutool/commit/74358b096550882422c80ca5b30c01b259562db3?
I believe it fixes the issue.

**Comment by wedgef5** [comment]
Confirmed fixed. Thanks!
